version: '3.8'

services:
  backend:
    build: backend/
    restart: on-failure
    command: npm run start
    ports:
      - 3000:3000
    depends_on:
      - bet_venture_database
    environment:
      DB_HOST: bet_venture_database
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 50s
      retries: 5

  bet_venture_database:
    image: mysql:latest
    container_name: bet_venture_database
    environment:
      MYSQL_ROOT_PASSWORD: senha-mysql
      MYSQL_DATABASE: bet_venture_database
      DB_HOST: bet_venture_database
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
